services:
  nest-backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: nest-backend
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:rw
      - /usr/src/app/node_modules
    depends_on:
      - nest-mysql
    networks:
      - web

  nest-mysql:
    container_name: nest-mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_HOST="%"
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    networks:
      - web
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    attach: false

networks:
  web:
    driver: bridge
