services:
  etab-nestjs-backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: etab-nestjs-backend
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:rw
    depends_on:
      - etab-nestjs-postgres
    networks:
      - web

  etab-nestjs-postgres:
    container_name: etab-nestjs-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    networks:
      - web
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      retries: 3
      timeout: 5s


networks:
  web:
    driver: bridge
