services:
  next-backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: eTab-NestJS-Backend
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:rw
    depends_on:
      - eTab-NestJS-postgres
    networks:
      - web

  eTab-NestJS-postgres:
    container_name: eTab-NestJS-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - 5432:5432  # PostgreSQL default port
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    networks:
      - web
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      retries: 3
      timeout: 5s


networks:
  web:
    driver: bridge
