export const AUTH_SERVICES_URL = "AUTH_SERVICES_URL"
export const AUTH_SERVICE_USER_LOGIN = "AUTH_SERVICE_USER_LOGIN"
export const AUTH_SERVICE_USER_PASSWORD = "AUTH_SERVICE_USER_PASSWORD"
export const AUTH_SERVICE_USER_TYPE = "AUTH_SERVICE_USER_TYPE"