export const TRADE_SERVICES_URL = "TRADE_SERVICES_URL";

export const TRADE_PROVIDER_MANAGER = "TRADE_PROVIDER_MANAGER";

export const TRADE_CODE_ERROR_ALREADY_HAS_BEEN_SAVED = 2;

export const TRADE_ORDER_MODE_FORWARD = 'forward';