export const TOKEN_TYPE = 'Bearer';
export const JWT_SECRET = 'JWT_SECRET';
export const JWT_EXPIRES_IN = 'JWT_EXPIRES_IN';
export const JWT_CART_EXPIRES_IN = 'JWT_CART_EXPIRES_IN';
export const JWT_REMEMBER_ME_EXPIRES_IN = 'JWT_REMEMBER_ME_EXPIRES_IN';