export const ORDER_ASYNC_SENDER_SCHEDULER = 'ORDER_ASYNC_SENDER_SCHEDULER';
export const ORDER_ASYNC_SENDER_SCHEDULER_ENABLED = 'ORDER_ASYNC_SENDER_SCHEDULER_ENABLED';

export const ORDER_STATE_RECEIVER_SCHEDULER = 'ORDER_STATE_RECEIVER_SCHEDULER';
export const ORDER_STATE_RECEIVER_LIMIT = 'ORDER_STATE_RECEIVER_LIMIT';
export const ORDER_STATE_RECEIVER_SCHEDULER_ENABLED = 'ORDER_STATE_RECEIVER_SCHEDULER_ENABLED';

export const ORDER_STATUS_DESCRIPTION_SCHEDULER = 'ORDER_STATUS_DESCRIPTION_SCHEDULER';
export const ORDER_STATUS_DESCRIPTION_SCHEDULER_ENABLED = 'ORDER_STATUS_DESCRIPTION_SCHEDULER_ENABLED';

export const TRADE_SEARCH_STATUS_DESCRIPTION_QUERY = 'SELECT id as status_id, type, code, description, order_index, is_manual FROM statuses_description';