export const ORDER_ASYNC_SENDER_SCHEDULER = 'ORDER_ASYNC_SENDER_SCHEDULER';
export const ORDER_ASYNC_SENDER_SCHEDULER_ENABLED = 'ORDER_ASYNC_SENDER_SCHEDULER_ENABLED';

export const ORDER_STATE_RECEIVER_SCHEDULER = 'ORDER_STATE_RECEIVER_SCHEDULER';
export const ORDER_STATE_RECEIVER_LIMIT = 'ORDER_STATE_RECEIVER_LIMIT';
export const ORDER_STATE_RECEIVER_SCHEDULER_ENABLED = 'ORDER_STATE_RECEIVER_SCHEDULER_ENABLED';